[package]
name = "crate-web"
version = "0.1.0"
authors = ["Heeill Wang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "1.4.0"
toml_edit = "0.2.0"